### ISSUE TITLE
【APP】健康管理アプリの管理者用サイト構築

### ISSUE THREAD

**Issue by kohei-okazaki** [kohei-okazaki/work-3g#556]
**背景**

健康情報管理アプリの以下はユーザエンド機能の提供としている
- 健康管理ダッシュボード(ha-dashboard)
- 健康管理API(ha-api)

バックエンド機能を提供する管理者用のサイトを新しく作る。

-----
**決まったこと or 思ったこと**

1. 折角、新しいWebアプリを作るなら何か新しい要素（言語、FW、ツール、ライブラリ）を入れたい。
2. Utilクラスや、DBアクセス機能は共通プロジェクトの方に
既に作られていて時間短縮の為、同じものを利用(ha-common, ha-dbなど)
3. 2.より、Java&Spring&Maven&MyBatisは決まり。

> 言語どうする？

→Java8（理由：既存の仕組みに乗っかるため）
> WebFWどうする？

→SpringBoot（理由：既存の仕組みに乗っかるため）
> Buildどうする？

→Maven（理由：既存の仕組みに乗っかるため）
> ORMどうする？

→MyBatis（理由：既存の仕組みに乗っかるため）
> フロントFWどうする？

→Vue.js（理由：SPA画面を作るため）
> プロジェクト名どうする？

→ha-root
> システム仕組みどうする？

以下の仕組みを基本とする
1. frontからAPIを呼ぶ
2. バックエンドで諸々処理
3. frontへJSON返却
4. Vueでうまく処理し画面描画
なのでJavaサーバは基本、HTMLは返さない。

-----
**TODO**
- [x] ha-assetにrootの開発環境構築手順を追加
- [x] お知らせ情報削除画面とそのAPIの実装
- [x] お知らせ情報一覧画面とそのAPIの実装
- [x] お知らせ情報登録画面とそのAPIの実装
- [x] お知らせ情報編集画面とそのAPIの実装
- [x] 管理API実行中は画面はローディング中の表示を出す
- [x] お知らせ情報登録/編集画面のタグ色のセレクトリストはcomponent化すること
- [x] お知らせ情報のJSONのtag-color, tag-nameはオブジェクト化し、画面に表示する際、そのタグの情報を見てcssを適用させる
- [x] API通信情報一覧画面でID押下時にAPIのタイムラインを表示する
- [x] ログイン後、ログインIDをhoverすると編集などへのメニューが出るように修正（ユーザホバーメニューに追加(https://vuetifyjs.com/en/components/menus/#open-on-hover)
- [x] 画面のTopへ戻るリンクを追加
- [x] 対応ブラウザ等の注意事項の追加（ユーザホバーメニューに追加）
- [x] ログイン後、TOP画面遷移前にユーザ情報取得APIを呼んで、vuexに情報を保存するように修正
- [x] 権限マスタ一覧取得APIでユーザ編集画面に表示する
- [x] ユーザ編集画面とそのAPIの実装
- [x] お知らせ情報更新画面で登録モードに戻すラジオボタンを用意
- [x] APIローディングはv-overlayを使う
- [x] ログイン後のTOP画面に「今月の健康管理ユーザ登録者数」「今月の健康情報登録数」をグラフで出力（TOP情報取得API）
- [x] 各画面遷移に権限をつける
- [x] ユーザ情報編集画面に項目追加（削除フラグ、パスワード、パスワード有効期限、備考）
- [x] 健康情報編集機能を追加（健康情報編集API）
- [x] 開発用リンクのサイトをAWSS3静的ホスティングサイトに移行（https://github.com/kohei-okazaki/work-3g/issues/638）
- [x] 管理者用サイトのドキュメントを作成
- [x] メモ機能追加（メモ一覧/登録/更新/削除API）
- [x] 健康情報編集をモーダル化
- [x] お知らせ情報編集をモーダル化
- [x] アカウント情報編集機能を追加（アカウント情報編集API）
- [x] 健康情報一覧画面にページング処理を入れる
- [x] アカウント情報一覧画面にページング処理を入れる
- [x] API通信情報一覧画面にページング処理を入れる
- [x] メモ情報一覧画面にページング処理を入れる
- [x] お知らせ情報一覧画面(root)にページング処理を入れる
- [x] お知らせ情報一覧画面(dashboard)にページング処理を入れる

-----
**機能一覧**
1. ログイン認証
2. ユーザ情報登録/編集
3. アカウント情報一覧/編集(to DB)
4. API通信情報一覧/編集(to DB)
5. 健康情報一覧/編集(to DB)
6. お知らせ情報一覧/登録/編集/削除(to S3)
7. メモ情報一覧/登録/編集/削除(to S3)

※適宜追加予定

**Comment by kohei-okazaki** [comment]
管理者サイト作成完了
